# plugins:
#   - jekyll-relative-links
# relative_links:
#   enabled: true
#   collections: true
# include:
#   - README.md

title: "Sugarverse Whitepaper v0.1"
remote_theme: pmarsceill/just-the-docs
# color_scheme: "dark"
search_enabled: false
